[project]
name = "bike-sharing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Farhan Muzaffar", email = "muzaffarfarhan@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
bike-sharing = "bike_sharing:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
